[package]
authors = ["David Fisher <ddfisher@dropbox.com>", "clemens"]
name = "ruba"
version = "0.1.0"

[dependencies]
csv = "0.15.0"
heapsize = "0.3.8"
itertools = "0.5.9"
nom = "^2.1"
num = "0.1.36"
regex = "0.2"
rustyline = "1.0.0"
serde_json = "0.9.6"
time = "0.1.36"
